// 此文件由脚本自动生成，请勿手动编辑
// Generated by update-subscription-config script at 2025-07-14T12:57:26.636Z

export interface DataSourceEntity {
  entityId: string;
  displayName: string;
  dataType: 'info' | 'strategy';
  description?: string;
  category?: string;
  enabled: boolean; // 是否启用订阅
}

// 订阅配置
export const subscriptionConfig: DataSourceEntity[] = [
  {
    entityId: "6d01bcf2-a61a-43e1-bfd1-6f173e0ec856",
    displayName: "⚡ TechFlow Crypto News Flash",
    dataType: "info",
    description: "Breaking crypto news as it happens! 🔥 Get exclusive TechFlow insights on DeFi, NFTs, Web3, and blockchain innovations. Expert-curated content delivers policy updates, project launches, and market analysis within 30 minutes of major events. Stay informed, stay ahead! 📱 Professional editorial team ensures quality over noise.\n",
    category: "crypto",
    enabled: true,
  },
  {
    entityId: "a9544f9d-335e-4457-99ed-142477fd6bcd",
    displayName: "⚫️ Aptos Ecosystem Portfolio",
    dataType: "strategy",
    description: "Position in APT for Move language adoption upside while capturing liquid staking growth through AMI, DeFi expansion via THL, and RWA innovation through PROPS to maximize Aptos ecosystem alpha generation.",
    category: "other",
    enabled: false,
  },
  {
    entityId: "5d7bd150-5675-4889-bc39-e3ba85277174",
    displayName: "🎓 Zacks Investment Research Center",
    dataType: "strategy",
    description: "Wall Street-grade investment analysis and research! 🏛️ Access authoritative Zacks reports with deep-dive stock analysis, fund evaluations, and macroeconomic trends. Professional analyst insights, investment strategies, risk assessments, and earnings forecasts updated daily. Make rational, data-driven investment decisions! 💼\n",
    category: "other",
    enabled: true,
  },
  {
    entityId: "15985cd0-90cf-4907-8b95-f7d735563277",
    displayName: "📊 CoinGecko Crypto Intelligence Hub",
    dataType: "info",
    description: "Real-time crypto market intelligence at your fingertips! 📊 Track trending cryptocurrencies, top gainers/losers, and price movements with official CoinGecko data. Updated every 30 minutes to keep you ahead of market opportunities and investment trends! 💰 Features comprehensive coin analysis, market cap rankings, and volume alerts for smart trading decisions.\n",
    category: "crypto",
    enabled: false,
  },
  {
    entityId: "db5df675-6d64-402c-8b2f-e63b7675ad74",
    displayName: "📰 PANews Crypto Digest",
    dataType: "info",
    description: "Authoritative Chinese crypto news and global insights! PANews professional team curates worldwide crypto developments with Chinese-language deep analysis covering Bitcoin, Ethereum, DeFi, and NFT ecosystems. Daily selection of important news with expert translation of premium international content. Navigate the global crypto landscape with ease! 🌏\n",
    category: "crypto",
    enabled: true,
  },
  {
    entityId: "e124b595-c58c-4ecb-a37a-52ccff5d8601",
    displayName: "🔵 Sui Ecosystem Portfolio",
    dataType: "strategy",
    description: "Accumulate SUI for parallel execution technology premium while leveraging CETUS for DeFi infrastructure growth and BUCK for stablecoin protocol expansion to capture Sui's technical advantages.",
    category: "other",
    enabled: false,
  },
  {
    entityId: "f0feb236-5a25-43a3-bb3c-df6fd638651c",
    displayName: "🟠 BSC Ecosystem Portfolio",
    dataType: "strategy",
    description: "Target BNB for low-cost DeFi access and exchange ecosystem benefits while maximizing yield through CAKE's farming rewards and XVS lending markets to exploit BSC's cost advantage over Ethereum.",
    category: "other",
    enabled: false,
  },
  {
    entityId: "49463c3c-ae71-4736-85c9-14dd613fc32e",
    displayName: "🟢 Solana Ecosystem Portfolio",
    dataType: "strategy",
    description: "Build SOL exposure for speed and cost efficiency leadership while rotating between RAY for liquidity dominance, JUP for trading volume growth, and PYTH for oracle infrastructure value capture.",
    category: "other",
    enabled: false,
  },
  {
    entityId: "4d600581-57e7-4902-83b5-f38f974662aa",
    displayName: "Aptos Info Hub",
    dataType: "info",
    description: "Comprehensive information hub for the Aptos blockchain ecosystem. Features key metrics, network statistics, developer updates, ecosystem news, protocols, marketplaces, and strategic insights about the Aptos blockchain and its growing ecosystem.",
    category: "true",
    enabled: false,
  },
  {
    entityId: "4e44f200-076d-49c8-bd7c-356859d459b2",
    displayName: "Crypto KOL Market Insights",
    dataType: "info",
    description: "Premium crypto market insights and analysis from reputable Key Opinion Leaders (KOLs) in the cryptocurrency space. Features expert opinions, market predictions, trading signals, and strategic investment advice from top crypto influencers and analysts.",
    category: "crypto",
    enabled: true,
  },
  {
    entityId: "bb9c51f9-3c53-4745-94ba-10481f56dc68",
    displayName: "Portfolio Analysis",
    dataType: "strategy",
    description: undefined,
    category: "other",
    enabled: false,
  }
];

// 获取启用的订阅配置
export function getEnabledSubscriptions(): DataSourceEntity[] {
  return subscriptionConfig.filter(entity => entity.enabled);
}

// 根据分类获取配置
export function getSubscriptionsByCategory(category: string): DataSourceEntity[] {
  return subscriptionConfig.filter(entity => entity.category === category);
}

// 根据entityId获取配置
export function getSubscriptionConfig(entityId: string): DataSourceEntity | undefined {
  return subscriptionConfig.find(entity => entity.entityId === entityId);
}
